pub mod automatic_home;
pub mod automation;
pub mod boot;
pub mod browser_preferences;
pub mod browsing;
pub mod client;
pub mod confirmation;
pub mod coordination;
pub mod copy_out;
pub mod layout;
pub mod maintenance;
pub mod model;
pub mod operations;
pub mod package_hooks;
pub mod package_transaction;
pub mod recovery;
pub mod retention;
pub mod rollback;
pub mod snapshot_search;
pub mod space;
pub mod store;
pub mod targets;
pub mod transaction;

pub const CONTRACT_VERSION: u32 = 11;
pub const DEPLOYMENT_SCHEMA_VERSION: u32 = 1;
pub const SNAPSHOT_ROOT: &str = "/.snapshots/anduinos";
pub const DBUS_NAME: &str = "com.anduinos.TimebackMachine1";
pub const DBUS_PATH: &str = "/com/anduinos/TimebackMachine1";
pub const DBUS_INTERFACE: &str = "com.anduinos.TimebackMachine1";
