#!/bin/sh
set -e

PREREQ=""

prereqs()
{
    echo "$PREREQ"
}

case "${1:-}" in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/libexec/anduinos-timeback-initramfs
copy_exec /usr/bin/btrfs
manual_add_modules btrfs
