[package]
name = "anduinos-waypoint-notifier"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "AnduinOS Waypoint desktop notification listener"

[[bin]]
name = "anduinos-waypoint-notifier"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
log.workspace = true
env_logger = "0.11"
futures-util = "0.3"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
tokio = { version = "1", features = ["macros", "rt", "time"] }
waypoint-common = { path = "../waypoint-common" }
zbus = { version = "4.0", default-features = false, features = ["tokio"] }
